### ISSUE TITLE
Prevent VMSet sub-resource deletion recovery

### ISSUE THREAD

**Issue by abays** [openstack-k8s-operators/osp-director-operator#139]
We currently handle controlled scale-down for VMSet, but we need to address the scenario where someone tries to manually delete the underlying VirtualMachine resources.

**Comment by stuggi** [comment]
should we set a finalizer that this can not happen?

**Comment by abays** [comment]
I changed this to VMSet only.  If we want to do this for BaremetalSet, I think it's a different consideration anyhow.
