### ISSUE TITLE
TLS everywhere testing

### ISSUE THREAD

**Issue by dprince** [openstack-k8s-operators/osp-director-operator#150]
15:58 <mschuppert> hi! do we support tls-everywhere with predeployed servers in tripleo? https://docs.openstack.org/project-deploy-guide/tripleo-docs/latest/features/deployed_server.html
15:59 <ade_lee> yes
15:59 <ade_lee> that was one of the main drivers for developing tripleo-ipa
16:00 <mschuppert> cool, do we have some doc on that?
16:00 <ade_lee> because we could not do tls-e with novajoin with predeployed  servers
16:00 <mschuppert> which release will that be?
16:00 <ade_lee> train +
16:01 <ade_lee> I think its in the upstream docs .. and should be the default implementation for U or V+

**Comment by JAORMX** [comment]
you might want to start leveraging [cert-manager](https://cert-manager.io/) for a more "cloud-native" approach to certs or leverage the [FreeIPA operator](https://github.com/freeipa/freeipa-operator) if you want to keep using FreeIPA/IDM
