### ISSUE TITLE
mariadb max connections limit issue

### ISSUE THREAD

**Issue by snecklifter** [openstack-k8s-operators/osp-director-operator#236]
I'm hitting a max connections limit when running the playbookgenerator.
I worked around this by raising the limit after the mariadb pod has started but before the playbook generator has started with:

```
oc rsh mariadb-default mysql -u root -ppassword -Bse "set global max_connections = 301;"
```

but it might be an idea to consider increasing this whatever Director uses - 1024?

**Comment by snecklifter** [comment]
Just to confirm I had to boost this up to 1024 to get the playbook run to complete.

**Comment by snecklifter** [comment]
I can see it should be getting set here:

https://github.com/openstack-k8s-operators/osp-director-operator/blob/master/templates/openstackephemeralheat/bin/galera.cnf#L17

but

``` 
MariaDB [mysql]> show variables like "max_connections";
+-----------------+-------+
| Variable_name   | Value |
+-----------------+-------+
| max_connections | 151   |
+-----------------+-------+
1 row in set (0.001 sec)

MariaDB [mysql]> show variables like "open_files_limit";
+------------------+-------+
| Variable_name    | Value |
+------------------+-------+
| open_files_limit | 32262 |
+------------------+-------+
1 row in set (0.001 sec)
```

**Comment by snecklifter** [comment]
Might be just a permissions issue?

```
sh-4.4$ ls -l /etc/my.cnf.d/galera.cnf 
-rw-------. 1 root root 718 May 13 09:13 /etc/my.cnf.d/galera.cnf
sh-4.4$ ps uax | grep -i mysqld
mysql          7  1.9  0.2 12027508 1150524 ?    Ssl  09:13   0:17 /usr/libexec/mysqld --user=mysql
```

**Comment by dprince** [comment]
Resolved in https://github.com/openstack-k8s-operators/osp-director-operator/pull/238

**Comment by snecklifter** [comment]
Tested and looks good, thanks!
