### ISSUE TITLE
image_downloader Dockerfile issues

### ISSUE THREAD

**Issue by mykaul** [openstack-k8s-operators/osp-director-operator#621]
- [ ] Using somewhat outdated container image - centos:centos7 - would be nice to use ubi8.
- [ ] Even nicer - moving to ubi-minimal image
- [ ] Missing cleanup after the dnf/yum upgrade and install commands.

**Comment by mykaul** [comment]
https://github.com/openstack-k8s-operators/osp-director-operator/pull/620 answers the 1st issue.

**Comment by olliewalsh** [comment]
Added `dnf clean all` in #627

**Comment by olliewalsh** [comment]
Using Jira now so have created https://issues.redhat.com/browse/OSPK8-630 to track this
